=== Ditti4/SteamSkinInstaller/SteamSkinInstaller/skins.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
<xs:element name="skins">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="skin" maxOccurs="unbounded">
        <xs:complexType>
          <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="author" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="website" type="xs:string"/>
            <xs:element name="download">
              <xs:complexType>
                <xs:all>
                  <xs:element name="method" type="xs:string" minOccurs="0"/>
                  <xs:element name="devianturl" type="xs:string" minOccurs="0"/>
                  <xs:element name="githubuser" type="xs:string" minOccurs="0"/>
                  <xs:element name="githubrepo" type="xs:string" minOccurs="0"/>
                  <xs:element name="githubusetags" type="xs:boolean" minOccurs="0"/>
                </xs:all>
              </xs:complexType>
            </xs:element>
            <xs:element name="version" minOccurs="0">
              <xs:complexType>
                <xs:all>
                  <xs:element name="pattern" type="xs:string" minOccurs="0"/>
                  <xs:element name="patterngroup" type="xs:int" minOccurs="0"/>
                  <xs:element name="matchurl" type="xs:string" minOccurs="0"/>
                </xs:all>
              </xs:complexType>
            </xs:element>
          </xs:all>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== Ditti4/SteamSkinInstaller/SteamSkinInstaller/skins.xml
<?xml version="1.0" encoding="utf-8" ?>
<skins xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="skins.xsd">
  <skin>
    <name>Metro for Steam</name>
    <author>BoneyardBrew</author>
    <description>Lorem Ipsum</description>
    <website>http://metroforsteam.com</website>
    <download>
      <method>deviantart</method>
      <devianturl>http://boneyardbrew.deviantart.com/art/Metro-for-Steam-3-9-1-292419787</devianturl>
    </download>
    <version>
      <pattern>Metro for Steam - ((\d\.)*)</pattern>
      <patterngroup>2</patterngroup>
    </version>
  </skin>
  <skin>
    <name>Pressure for Steam</name>
    <author>DirtDiglett</author>
    <description>Lorem Ipsum</description>
    <website>http://hydra.tf/pressure</website>
    <download>
      <method>github</method>
      <githubuser>dirtdiglett</githubuser>
      <githubrepo>pressure-for-steam</githubrepo>
    </download>
  </skin>
</skins>
